datagrid:
    orcrm-contact-requests-grid-extended:
        extends: orcrm-contact-requests-grid
        source:
            query:
                select:
                    - step.label as statusLabel
                join:
                    left:
                        - { join: cr.workflowStep, alias: step }
        columns:
            statusLabel:
                type:  translatable
                label: orocrm.contactus.contactrequest.status.label
        sorters:
            columns:
                statusLabel:
                    data_name: statusLabel
        filters:
            columns:
                statusLabel:
                    type: entity
                    data_name: cr.workflowStep
                    options:
                        field_type: oro_workflow_step_select
                        field_options:
                            workflow_entity_class: %orocrm_contact_us.contactrequest.entity.class%
