oro_menu_config:
    items:
        orocrm_contactus_requests:
            label: 'Contact Requests'
            route: 'orocrm_contactus_request_index'

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        orocrm_contactus_requests: ~
