oro_menu_config:
    items:
        orocrm_magento_contactus_requests:
            label: orocrm.magentocontactus.contactrequest.entity_plural_label
            route: orocrm_magento_contactus_request_index
            extras:
                routes: ['orocrm_magento_contactus_request_*']
    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        orocrm_magento_contactus_requests: ~

oro_titles:
    orocrm_magento_contactus_request_index:   ~
    orocrm_magento_contactus_request_view:    %%request.clientName%%
    orocrm_magento_contactus_request_create:  Create contact request
    orocrm_magento_contactus_request_update:  %%request.clientName%% - Edit
