oro_menu_config:
    items:
        orocrm_contactus_requests:
            label: 'Contact Requests'
            route: 'orocrm_contactus_request_index'
            extras:
                routes: ['orocrm_contactus_request_*']
    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        orocrm_contactus_requests: ~

oro_titles:
    orocrm_contactus_request_index:   ~
    orocrm_contactus_request_view:    %%request.clientName%%'s contact request
    orocrm_contactus_request_create:  Create contact request
    orocrm_contactus_request_update:  %%request.clientName%%'s contact request - Edit
