parameters:
    orocrm_contact_us.embedded_form.class:   OroCRM\Bundle\ContactUsBundle\Form\Type\ContactRequestType
    orocrm_contact_us.datagrid.helper.class:  OroCRM\Bundle\ContactUsBundle\Datagrid\ContactRequestDatagridHelper

services:
    orocrm_contact_us.embedded_form:
        class: %orocrm_contact_us.embedded_form.class%
        tags:
            - { name: oro_embedded_form, label: orocrm.contactus.contactrequest.entity_label }

    orocrm_contact_us.datagrid.helper:
        class: %orocrm_contact_us.datagrid.helper.class%
        arguments:
            - @doctrine.orm.entity_manager
