OroCRM\Bundle\MagentoContactUsBundle\Entity\ContactRequest:
    properties:
        firstName:
            - NotBlank: ~
            - Length:
                max: 100
        lastName:
            - NotBlank: ~
            - Length:
                max: 100
        preferredContactMethod:
            - NotBlank: ~
        emailAddress:
            - Email: ~
        comment:
            - NotBlank: ~
    constraints:
        - Callback:
            methods:
                - [ OroCRM\Bundle\MagentoContactUsBundle\Validator\ContactRequestCallbackValidator, validate]
