workflows:
    orocrm_contact_us_contact_request:
        label:   'Contact Request'
        enabled:  true
        entity:   OroCRM\Bundle\ContactUsBundle\Entity\ContactRequest
        entity_attribute: request
        start_step: open
        steps:
            open:
                label: 'Open'
                order: 10
                allowed_transitions:
                    - log_call
#                    - send_email
                    - resolve
            contacted:
                label: 'Contacted'
                order: 20
                allowed_transitions:
                    - log_call
#                    - send_email
                    - resolve
#                    - convert_to_opportunity
#                    - convert_to_lead
            resolved:
                label: 'Resolved'
                order: 40
#            converted_to_opportunity:
#                label: 'Converted to opportunity'
#                order: 30
#            converted_to_lead:
#                label: 'Converted to lead'
#                order: 30

        attributes:
            # Call related fields
            call:
                label: 'Call log'
                type: entity
                options:
                    class: OroCRM\Bundle\CallBundle\Entity\Call
            call_phone_number:
                label: 'Phone number'
                type: string
            call_subject:
                label: 'Call subject'
                type: string
            call_date:
                label: 'Call date'
                type: object
                options:
                    class: DateTime
            call_direction:
                label: 'Call direction'
                type: entity
                options:
                    class: OroCRM\Bundle\CallBundle\Entity\CallDirection
            call_status:
                label: 'Call status'
                type: entity
                options:
                    class: OroCRM\Bundle\CallBundle\Entity\CallStatus
            call_duration:
                label: 'Call duration'
                type: object
                options:
                    class: DateTime

            # Other workflow attributes
            feedback:
                label: 'Feedback'
                type: string
                property_path: request.feedback
            account:
                label: 'Account'
                type: entity
                options:
                    class: OroCRM\Bundle\AccountBundle\Entity\Account
            contact:
                label: 'Contact'
                type: entity
                options:
                    class: OroCRM\Bundle\ContactBundle\Entity\Contact
        transitions:
            log_call:
                label:        'Log call'
                step_to:      contacted
                is_start:     true
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-phone'
                transition_definition: log_call_definition
                form_options:
                    attribute_fields:
                        call_phone_number:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        call_subject:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        call_date:
                            form_type: oro_datetime
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        account:
                            form_type: orocrm_account_select
                            options:
                                required: false
                                label: 'Related to'
                        contact:
                            form_type: orocrm_contact_select
                            options:
                                required: false
                                label: 'Related contact'
                        call_direction:
                            form_type: entity
                            options:
                                class: OroCRM\Bundle\CallBundle\Entity\CallDirection
                                property: label
                                required: true
                                constraints:
                                    - NotBlank: ~
                        call_duration:
                            form_type: oro_time_interval
                            options:
                                required: false
                                widget: single_text
                                with_seconds: true
                        feedback:
                            form_type: textarea
                            options:
                                required: false
                    init_actions:
                        - @assign_value:
                            conditions:
                                @and:
                                    - @empty:     $call_phone_number
                                    - @not_empty: $request.phone
                            parameters: [$call_phone_number, $request.phone]
                        - @create_datetime:
                            attribute: $call_date
                        - @create_datetime:
                            time: '00:00:00'
                            attribute: $call_duration
            resolve:
                label:      'Resolve'
                step_to:    resolved
                is_start:   true
                is_unavailable_hidden: true
                transition_definition: resolve_definition
                form_options:
                    attribute_fields:
                        feedback:
                            form_type: textarea
                            options:
                                required: false

        transition_definitions:
            log_call_definition:
                pre_conditions:
                    @and:
                        - @equal:     [$request.status.name, 'open']
                        - @not_empty: $request.phone
                conditions:
                    @and:
                        - @not_empty:
                            parameters: $call_phone_number
                            message:    'Phone number must be set'
                        - @not_empty:
                            parameters: $call_subject
                            message:    'Call subject must be set'
                        - @not_empty:
                            parameters: $call_date
                            message:   'Call date must be set'
                        - @not_empty:
                            parameters: $call_direction
                            message:    'Call direction must be chosen'
                post_actions:
                    - @find_entity:
                        class:       OroCRM\Bundle\CallBundle\Entity\CallStatus
                        identifier:  'completed'
                        attribute:   $call_status
                    - @create_entity: # create Call
                        class:        OroCRM\Bundle\CallBundle\Entity\Call
                        attribute:    $call
                        data:
                            relatedContact: $contact
                            relatedAccount: $account
                            subject:        $call_subject
                            phoneNumber:    $call_phone_number
                            notes:          $feedback
                            callDateTime:   $call_date
                            callStatus:     $call_status
                            duration:       $call_duration
                            direction:      $call_direction
                    - @call_method:
                        method:            'addCall'
                        object:            $request
                        method_parameters: [$call]
            resolve_definition:
                pre_conditions:
                    @equal: [$request.status.name, 'open']
                post_actions:
                    - @find_entity:
                        class:       OroCRM\Bundle\ContactUsBundle\Entity\ContactRequestStatus
                        identifier: 'resolved'
                        attribute:   $request.status
